/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfEmployee;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import enums.Gender;

import menajeremployee.Employee;
/**
 *
 * @author mihail
 */
public class AddDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddDialog
     */

    private Employee result;
    
    public AddDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Employee getResult(){
      return this.result;
    }

    /*public void setResultAdd(){
      jSubmit.setVisible(true);
      jEdit.setVisible(false);
      this.setVisible(true);
    } */     
    
    public void setResultEdit(Employee emp){
      DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
      this.result=emp;
      //jSubmit.setVisible(false);
      //jEdit.setVisible(true);
      
      jTname.setText(emp.getName());
      jTsurname.setText(emp.getsurName());;
      jTsalary.setText(String.valueOf(emp.getSalary()));
      jFormattedThireDay.setText(String.valueOf(emp.getHireDay().format(formatter)));
      jFormattedTbirthDay.setText(String.valueOf(emp.getBirthDay().format(formatter)));
      jCgender.setSelectedItem(String.valueOf(emp.getGender()));
      this.setVisible(true);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLname = new javax.swing.JLabel();
        jLsurname = new javax.swing.JLabel();
        jLsalary = new javax.swing.JLabel();
        jLhireDay = new javax.swing.JLabel();
        jTname = new javax.swing.JTextField();
        jTsurname = new javax.swing.JTextField();
        jTsalary = new javax.swing.JTextField();
        jFormattedThireDay = new javax.swing.JFormattedTextField();
        jCgender = new javax.swing.JComboBox<>();
        jSubmit = new javax.swing.JButton();
        jLbirthDay = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jFormattedTbirthDay = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLname.setText("Nume");

        jLsurname.setText("Prenume");

        jLsalary.setText("Salariu");

        jLhireDay.setText("Data angajarii");

        jFormattedThireDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        jCgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));

        jSubmit.setText("Inregistrare");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jLbirthDay.setText("Data nasterii");

        jGender.setText("Genul");

        jFormattedTbirthDay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLsalary)
                            .addComponent(jLhireDay)
                            .addComponent(jLbirthDay)
                            .addComponent(jGender))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTsalary)
                            .addComponent(jFormattedThireDay)
                            .addComponent(jCgender, 0, 202, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSubmit))
                            .addComponent(jFormattedTbirthDay)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLsurname)
                            .addComponent(jLname))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTname)
                            .addComponent(jTsurname))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLsalary, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedThireDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLhireDay, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbirthDay)
                    .addComponent(jFormattedTbirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGender))
                .addGap(18, 18, 18)
                .addComponent(jSubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
        /*System.out.println(jTname.getText());
        System.out.println(jTsurname.getText());
        System.out.println(jTsalary.getText());
        System.out.println(jFormattedThireDay.getText());
        System.out.println(jFormattedTbirthDay.getText());
        System.out.println(jCgender.getItemAt(jCgender.getSelectedIndex()));
        */
        
        /*int id;
        if(this.result == null){
          id=0;
        }else{
          id=this.result.getId();
        }
        System.out.println("jFormattedTbirthDay1="+jFormattedTbirthDay.getText());
        System.out.println("jFormattedTbirthDay="+String.valueOf(LocalDate.parse(jFormattedTbirthDay.getText(),formatter)));
        */
        if(this.result == null){
        this.result = new Employee(0,jTname.getText(),jTsurname.getText(),Double.parseDouble(jTsalary.
                      getText()),LocalDate.parse(jFormattedThireDay.getText(),formatter),
                      LocalDate.parse(jFormattedTbirthDay.getText(),formatter),
                      Gender.valueOf(jCgender.getItemAt(jCgender.getSelectedIndex())));
        }else{
        this.result = new Employee(this.result.getId(),this.result.getIdnp(),jTname.getText(),jTsurname.getText(),Double.parseDouble(jTsalary.
                      getText()),LocalDate.parse(jFormattedThireDay.getText(),formatter),
                      LocalDate.parse(jFormattedTbirthDay.getText(),formatter),
                      Gender.valueOf(jCgender.getItemAt(jCgender.getSelectedIndex())));        
        }
        this.setVisible(false);
    }//GEN-LAST:event_jSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddDialog dialog = new AddDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCgender;
    private javax.swing.JFormattedTextField jFormattedTbirthDay;
    private javax.swing.JFormattedTextField jFormattedThireDay;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jLbirthDay;
    private javax.swing.JLabel jLhireDay;
    private javax.swing.JLabel jLname;
    private javax.swing.JLabel jLsalary;
    private javax.swing.JLabel jLsurname;
    private javax.swing.JButton jSubmit;
    private javax.swing.JTextField jTname;
    private javax.swing.JTextField jTsalary;
    private javax.swing.JTextField jTsurname;
    // End of variables declaration//GEN-END:variables
}
